#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

# Regenerate all the autotools files.
autoreconf -i --force

# Generate manual pages.
version=`grep '^krb5-strength' NEWS | head -1 | cut -d' ' -f2`
pod2man --release="$version" --center='krb5-strength' \
    tools/cdbmake-wordlist > tools/cdbmake-wordlist.1
pod2man --release="$version" --center='krb5-strength' \
    tools/heimdal-history > tools/heimdal-history.1
pod2man --release="$version" --center='krb5-strength' \
    tools/heimdal-strength.pod > tools/heimdal-strength.1

# Generate the C version of our password test data.
for data in tests/data/passwords/*.json ; do
    tests/data/passwords/make-c-data "$data" \
        > $(echo "$data" | sed 's/\.json$/.c/')
done

# Generate the CDB database from the test wordlist for plugin tests.
tools/cdbmake-wordlist tests/data/wordlist
