#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

# Regenerate all the autotools files.
autoreconf -i --force

# Generate manual pages.
version=`grep '^krb5-strength' NEWS | head -1 | cut -d' ' -f2`
pod2man --release="$version" --center='krb5-strength' \
    external/heimdal-strength.pod > external/heimdal-strength.1
pod2man --release="$version" --center='krb5-strength' \
    tools/cdbmake-wordlist > tools/cdbmake-wordlist.1

# Generate the C version of our password test data.
tests/data/make-c-data tests/data/cracklib.json > tests/data/cracklib.c
