#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

autoreconf -i --force
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^krb5-strength' NEWS | head -1 | cut -d' ' -f2`
pod2man --release="$version" --center='krb5-strength' \
    external/heimdal-strength.pod > external/heimdal-strength.1
